export type WordPair = {
  civilianWord: string
  spyWord: string
}

export const wordPairs: WordPair[] = [
  { civilianWord: 'Burger', spyWord: 'Sandwich' },
  { civilianWord: 'Pizza', spyWord: 'Flatbread' },
  { civilianWord: 'Ramen', spyWord: 'Noodles' },
  { civilianWord: 'Coffee', spyWord: 'Tea' },
  { civilianWord: 'Pancakes', spyWord: 'Waffles' },
  { civilianWord: 'Ice Cream', spyWord: 'Gelato' },
  { civilianWord: 'Donut', spyWord: 'Bagel' },
  { civilianWord: 'Taco', spyWord: 'Burrito' },
  { civilianWord: 'Sushi', spyWord: 'Kimbap' },
  { civilianWord: 'Fries', spyWord: 'Chips' },
  { civilianWord: 'Airport', spyWord: 'Train Station' },
  { civilianWord: 'Hotel', spyWord: 'Resort' },
  { civilianWord: 'Hospital', spyWord: 'Clinic' },
  { civilianWord: 'Library', spyWord: 'Bookstore' },
  { civilianWord: 'Cinema', spyWord: 'Theater' },
  { civilianWord: 'Museum', spyWord: 'Gallery' },
  { civilianWord: 'Beach', spyWord: 'Pool' },
  { civilianWord: 'Gym', spyWord: 'Studio' },
  { civilianWord: 'Market', spyWord: 'Grocery' },
  { civilianWord: 'Office', spyWord: 'Coworking Space' },
  { civilianWord: 'Teacher', spyWord: 'Professor' },
  { civilianWord: 'Doctor', spyWord: 'Nurse' },
  { civilianWord: 'Chef', spyWord: 'Baker' },
  { civilianWord: 'Pilot', spyWord: 'Flight Attendant' },
  { civilianWord: 'Police Officer', spyWord: 'Detective' },
  { civilianWord: 'Photographer', spyWord: 'Videographer' },
  { civilianWord: 'Singer', spyWord: 'Dancer' },
  { civilianWord: 'Driver', spyWord: 'Rider' },
  { civilianWord: 'Designer', spyWord: 'Artist' },
  { civilianWord: 'Programmer', spyWord: 'Engineer' },
  { civilianWord: 'Phone', spyWord: 'Tablet' },
  { civilianWord: 'Laptop', spyWord: 'Desktop' },
  { civilianWord: 'Backpack', spyWord: 'Suitcase' },
  { civilianWord: 'Umbrella', spyWord: 'Raincoat' },
  { civilianWord: 'Watch', spyWord: 'Clock' },
  { civilianWord: 'Glasses', spyWord: 'Sunglasses' },
  { civilianWord: 'Wallet', spyWord: 'Purse' },
  { civilianWord: 'Notebook', spyWord: 'Journal' },
  { civilianWord: 'Headphones', spyWord: 'Earbuds' },
  { civilianWord: 'Camera', spyWord: 'Projector' },
  { civilianWord: 'Basketball', spyWord: 'Volleyball' },
  { civilianWord: 'Soccer', spyWord: 'Futsal' },
  { civilianWord: 'Tennis', spyWord: 'Badminton' },
  { civilianWord: 'Swimming', spyWord: 'Diving' },
  { civilianWord: 'Running', spyWord: 'Jogging' },
  { civilianWord: 'Boxing', spyWord: 'Wrestling' },
  { civilianWord: 'Chess', spyWord: 'Checkers' },
  { civilianWord: 'Bowling', spyWord: 'Billiards' },
  { civilianWord: 'Cycling', spyWord: 'Skating' },
  { civilianWord: 'Baseball', spyWord: 'Softball' },
  { civilianWord: 'Rain', spyWord: 'Storm' },
  { civilianWord: 'Sunrise', spyWord: 'Sunset' },
  { civilianWord: 'Mountain', spyWord: 'Hill' },
  { civilianWord: 'River', spyWord: 'Lake' },
  { civilianWord: 'Forest', spyWord: 'Garden' },
  { civilianWord: 'Snow', spyWord: 'Ice' },
  { civilianWord: 'Fire', spyWord: 'Candle' },
  { civilianWord: 'Moon', spyWord: 'Star' },
  { civilianWord: 'Island', spyWord: 'Peninsula' },
  { civilianWord: 'Desert', spyWord: 'Canyon' },
  { civilianWord: 'Birthday', spyWord: 'Anniversary' },
  { civilianWord: 'Wedding', spyWord: 'Engagement' },
  { civilianWord: 'Concert', spyWord: 'Festival' },
  { civilianWord: 'Meeting', spyWord: 'Interview' },
  { civilianWord: 'Vacation', spyWord: 'Staycation' },
  { civilianWord: 'Exam', spyWord: 'Quiz' },
  { civilianWord: 'Party', spyWord: 'Reunion' },
  { civilianWord: 'Dinner', spyWord: 'Lunch' },
  { civilianWord: 'Road Trip', spyWord: 'Commute' },
  { civilianWord: 'Sleepover', spyWord: 'Camping' },
  { civilianWord: 'Superhero', spyWord: 'Villain' },
  { civilianWord: 'Wizard', spyWord: 'Magician' },
  { civilianWord: 'Robot', spyWord: 'Android' },
  { civilianWord: 'Alien', spyWord: 'Astronaut' },
  { civilianWord: 'Pirate', spyWord: 'Sailor' },
  { civilianWord: 'Detective', spyWord: 'Spy' },
  { civilianWord: 'Dragon', spyWord: 'Dinosaur' },
  { civilianWord: 'Ghost', spyWord: 'Zombie' },
  { civilianWord: 'Castle', spyWord: 'Palace' },
  { civilianWord: 'Treasure', spyWord: 'Trophy' },
  { civilianWord: 'Croissant', spyWord: 'Bagel' },
  { civilianWord: 'Muffin', spyWord: 'Cupcake' },
  { civilianWord: 'Brownie', spyWord: 'Chocolate Cake' },
  { civilianWord: 'Cheesecake', spyWord: 'Flan' },
  { civilianWord: 'Macaron', spyWord: 'Cookie' },
  { civilianWord: 'Pretzel', spyWord: 'Breadstick' },
  { civilianWord: 'Hotdog', spyWord: 'Sausage Roll' },
  { civilianWord: 'Fried Chicken', spyWord: 'Chicken Nuggets' },
  { civilianWord: 'Steak', spyWord: 'Roast Beef' },
  { civilianWord: 'Meatballs', spyWord: 'Sausage' },
  { civilianWord: 'Spaghetti', spyWord: 'Lasagna' },
  { civilianWord: 'Mac and Cheese', spyWord: 'Carbonara' },
  { civilianWord: 'Curry', spyWord: 'Stew' },
  { civilianWord: 'Soup', spyWord: 'Broth' },
  { civilianWord: 'Salad', spyWord: 'Coleslaw' },
  { civilianWord: 'Smoothie', spyWord: 'Milkshake' },
  { civilianWord: 'Lemonade', spyWord: 'Iced Tea' },
  { civilianWord: 'Soda', spyWord: 'Sparkling Water' },
  { civilianWord: 'Chocolate', spyWord: 'Candy' },
  { civilianWord: 'Popcorn', spyWord: 'Nachos' },
  { civilianWord: 'Mango', spyWord: 'Peach' },
  { civilianWord: 'Apple', spyWord: 'Pear' },
  { civilianWord: 'Orange', spyWord: 'Tangerine' },
  { civilianWord: 'Grapes', spyWord: 'Raisins' },
  { civilianWord: 'Watermelon', spyWord: 'Melon' },
  { civilianWord: 'Pineapple', spyWord: 'Jackfruit' },
  { civilianWord: 'Strawberry', spyWord: 'Raspberry' },
  { civilianWord: 'Blueberry', spyWord: 'Blackberry' },
  { civilianWord: 'Avocado', spyWord: 'Guacamole' },
  { civilianWord: 'Tomato', spyWord: 'Cherry Tomato' },
  { civilianWord: 'Potato', spyWord: 'Sweet Potato' },
  { civilianWord: 'Carrot', spyWord: 'Radish' },
  { civilianWord: 'Corn', spyWord: 'Popcorn' },
  { civilianWord: 'Rice', spyWord: 'Quinoa' },
  { civilianWord: 'Oatmeal', spyWord: 'Cereal' },
  { civilianWord: 'Toast', spyWord: 'Garlic Bread' },
  { civilianWord: 'Butter', spyWord: 'Margarine' },
  { civilianWord: 'Cheese', spyWord: 'Cream Cheese' },
  { civilianWord: 'Yogurt', spyWord: 'Pudding' },
  { civilianWord: 'Eggs', spyWord: 'Omelet' },
  { civilianWord: 'Bank', spyWord: 'ATM' },
  { civilianWord: 'Pharmacy', spyWord: 'Drugstore' },
  { civilianWord: 'Bakery', spyWord: 'Cafe' },
  { civilianWord: 'Restaurant', spyWord: 'Diner' },
  { civilianWord: 'Mall', spyWord: 'Shopping Center' },
  { civilianWord: 'Park', spyWord: 'Playground' },
  { civilianWord: 'Zoo', spyWord: 'Aquarium' },
  { civilianWord: 'Stadium', spyWord: 'Arena' },
  { civilianWord: 'Classroom', spyWord: 'Lecture Hall' },
  { civilianWord: 'Cafeteria', spyWord: 'Food Court' },
  { civilianWord: 'Bus Stop', spyWord: 'Taxi Stand' },
  { civilianWord: 'Subway', spyWord: 'Underground Station' },
  { civilianWord: 'Parking Lot', spyWord: 'Garage' },
  { civilianWord: 'Gas Station', spyWord: 'Charging Station' },
  { civilianWord: 'Post Office', spyWord: 'Mailroom' },
  { civilianWord: 'Courthouse', spyWord: 'City Hall' },
  { civilianWord: 'Church', spyWord: 'Chapel' },
  { civilianWord: 'Temple', spyWord: 'Shrine' },
  { civilianWord: 'Apartment', spyWord: 'Condo' },
  { civilianWord: 'Mansion', spyWord: 'Villa' },
  { civilianWord: 'Farm', spyWord: 'Ranch' },
  { civilianWord: 'Harbor', spyWord: 'Marina' },
  { civilianWord: 'Bridge', spyWord: 'Tunnel' },
  { civilianWord: 'Highway', spyWord: 'Expressway' },
  { civilianWord: 'Alley', spyWord: 'Side Street' },
  { civilianWord: 'Balcony', spyWord: 'Patio' },
  { civilianWord: 'Basement', spyWord: 'Cellar' },
  { civilianWord: 'Attic', spyWord: 'Storage Room' },
  { civilianWord: 'Kitchen', spyWord: 'Dining Room' },
  { civilianWord: 'Bedroom', spyWord: 'Guest Room' },
  { civilianWord: 'Bathroom', spyWord: 'Powder Room' },
  { civilianWord: 'Laundry Room', spyWord: 'Utility Room' },
  { civilianWord: 'Elevator', spyWord: 'Escalator' },
  { civilianWord: 'Lobby', spyWord: 'Reception' },
  { civilianWord: 'Warehouse', spyWord: 'Factory' },
  { civilianWord: 'Laboratory', spyWord: 'Workshop' },
  { civilianWord: 'Studio Apartment', spyWord: 'Dorm Room' },
  { civilianWord: 'Bookshop', spyWord: 'Newsstand' },
  { civilianWord: 'Barbershop', spyWord: 'Salon' },
  { civilianWord: 'Spa', spyWord: 'Sauna' },
  { civilianWord: 'Dentist', spyWord: 'Orthodontist' },
  { civilianWord: 'Surgeon', spyWord: 'Physician' },
  { civilianWord: 'Paramedic', spyWord: 'Lifeguard' },
  { civilianWord: 'Firefighter', spyWord: 'Rescue Worker' },
  { civilianWord: 'Lawyer', spyWord: 'Judge' },
  { civilianWord: 'Accountant', spyWord: 'Auditor' },
  { civilianWord: 'Banker', spyWord: 'Cashier' },
  { civilianWord: 'Waiter', spyWord: 'Bartender' },
  { civilianWord: 'Barista', spyWord: 'Tea Master' },
  { civilianWord: 'Butcher', spyWord: 'Fishmonger' },
  { civilianWord: 'Farmer', spyWord: 'Gardener' },
  { civilianWord: 'Mechanic', spyWord: 'Technician' },
  { civilianWord: 'Electrician', spyWord: 'Plumber' },
  { civilianWord: 'Carpenter', spyWord: 'Builder' },
  { civilianWord: 'Architect', spyWord: 'Interior Designer' },
  { civilianWord: 'Journalist', spyWord: 'Reporter' },
  { civilianWord: 'Editor', spyWord: 'Publisher' },
  { civilianWord: 'Author', spyWord: 'Poet' },
  { civilianWord: 'Actor', spyWord: 'Comedian' },
  { civilianWord: 'Director', spyWord: 'Producer' },
  { civilianWord: 'Musician', spyWord: 'Composer' },
  { civilianWord: 'DJ', spyWord: 'Radio Host' },
  { civilianWord: 'Streamer', spyWord: 'Podcaster' },
  { civilianWord: 'Influencer', spyWord: 'Model' },
  { civilianWord: 'Athlete', spyWord: 'Coach' },
  { civilianWord: 'Referee', spyWord: 'Umpire' },
  { civilianWord: 'Scientist', spyWord: 'Researcher' },
  { civilianWord: 'Astronomer', spyWord: 'Meteorologist' },
  { civilianWord: 'Biologist', spyWord: 'Zoologist' },
  { civilianWord: 'Historian', spyWord: 'Archaeologist' },
  { civilianWord: 'Translator', spyWord: 'Interpreter' },
  { civilianWord: 'Librarian', spyWord: 'Archivist' },
  { civilianWord: 'Security Guard', spyWord: 'Bouncer' },
  { civilianWord: 'Janitor', spyWord: 'Housekeeper' },
  { civilianWord: 'Tailor', spyWord: 'Seamstress' },
  { civilianWord: 'Makeup Artist', spyWord: 'Hair Stylist' },
  { civilianWord: 'Remote Control', spyWord: 'Game Controller' },
  { civilianWord: 'Keyboard', spyWord: 'Piano' },
  { civilianWord: 'Mouse', spyWord: 'Trackpad' },
  { civilianWord: 'Monitor', spyWord: 'Television' },
  { civilianWord: 'Printer', spyWord: 'Scanner' },
  { civilianWord: 'Router', spyWord: 'Modem' },
  { civilianWord: 'Charger', spyWord: 'Power Bank' },
  { civilianWord: 'Flash Drive', spyWord: 'Memory Card' },
  { civilianWord: 'Speaker', spyWord: 'Subwoofer' },
  { civilianWord: 'Microphone', spyWord: 'Megaphone' },
  { civilianWord: 'Tripod', spyWord: 'Selfie Stick' },
  { civilianWord: 'Calculator', spyWord: 'Cash Register' },
  { civilianWord: 'Calendar', spyWord: 'Planner' },
  { civilianWord: 'Envelope', spyWord: 'Postcard' },
  { civilianWord: 'Stamp', spyWord: 'Sticker' },
  { civilianWord: 'Scissors', spyWord: 'Cutter' },
  { civilianWord: 'Tape', spyWord: 'Glue' },
  { civilianWord: 'Pen', spyWord: 'Marker' },
  { civilianWord: 'Pencil', spyWord: 'Crayon' },
  { civilianWord: 'Eraser', spyWord: 'Correction Tape' },
  { civilianWord: 'Ruler', spyWord: 'Measuring Tape' },
  { civilianWord: 'Stapler', spyWord: 'Paper Clip' },
  { civilianWord: 'Folder', spyWord: 'Binder' },
  { civilianWord: 'Desk', spyWord: 'Table' },
  { civilianWord: 'Chair', spyWord: 'Stool' },
  { civilianWord: 'Couch', spyWord: 'Armchair' },
  { civilianWord: 'Bed', spyWord: 'Mattress' },
  { civilianWord: 'Pillow', spyWord: 'Cushion' },
  { civilianWord: 'Blanket', spyWord: 'Comforter' },
  { civilianWord: 'Curtains', spyWord: 'Blinds' },
  { civilianWord: 'Lamp', spyWord: 'Lantern' },
  { civilianWord: 'Mirror', spyWord: 'Window' },
  { civilianWord: 'Doorbell', spyWord: 'Alarm' },
  { civilianWord: 'Key', spyWord: 'Keycard' },
  { civilianWord: 'Lock', spyWord: 'Padlock' },
  { civilianWord: 'Broom', spyWord: 'Mop' },
  { civilianWord: 'Vacuum', spyWord: 'Dustpan' },
  { civilianWord: 'Soap', spyWord: 'Shampoo' },
  { civilianWord: 'Towel', spyWord: 'Robe' },
  { civilianWord: 'Toothbrush', spyWord: 'Floss' },
  { civilianWord: 'Soccer Ball', spyWord: 'Basketball' },
  { civilianWord: 'Baseball Bat', spyWord: 'Cricket Bat' },
  { civilianWord: 'Golf Club', spyWord: 'Hockey Stick' },
  { civilianWord: 'Skateboard', spyWord: 'Scooter' },
  { civilianWord: 'Surfboard', spyWord: 'Paddleboard' },
  { civilianWord: 'Kayak', spyWord: 'Canoe' },
  { civilianWord: 'Skiing', spyWord: 'Snowboarding' },
  { civilianWord: 'Hiking', spyWord: 'Trekking' },
  { civilianWord: 'Camping', spyWord: 'Backpacking' },
  { civilianWord: 'Fishing', spyWord: 'Boating' },
  { civilianWord: 'Yoga', spyWord: 'Pilates' },
  { civilianWord: 'Weightlifting', spyWord: 'Powerlifting' },
  { civilianWord: 'Marathon', spyWord: 'Triathlon' },
  { civilianWord: 'Relay Race', spyWord: 'Sprint' },
  { civilianWord: 'Dodgeball', spyWord: 'Handball' },
  { civilianWord: 'Rugby', spyWord: 'American Football' },
  { civilianWord: 'Table Tennis', spyWord: 'Air Hockey' },
  { civilianWord: 'Archery', spyWord: 'Darts' },
  { civilianWord: 'Fencing', spyWord: 'Kendo' },
  { civilianWord: 'Martial Arts', spyWord: 'Karate' },
  { civilianWord: 'Cheerleading', spyWord: 'Gymnastics' },
  { civilianWord: 'Roller Skating', spyWord: 'Ice Skating' },
  { civilianWord: 'Climbing', spyWord: 'Bouldering' },
  { civilianWord: 'Horse Racing', spyWord: 'Polo' },
  { civilianWord: 'Wrestling Ring', spyWord: 'Boxing Ring' },
  { civilianWord: 'Scoreboard', spyWord: 'Timer' },
  { civilianWord: 'Medal', spyWord: 'Ribbon' },
  { civilianWord: 'Trophy Case', spyWord: 'Display Shelf' },
  { civilianWord: 'Locker Room', spyWord: 'Changing Room' },
  { civilianWord: 'Whistle', spyWord: 'Air Horn' },
  { civilianWord: 'Helmet', spyWord: 'Cap' },
  { civilianWord: 'Jersey', spyWord: 'Uniform' },
  { civilianWord: 'Sneakers', spyWord: 'Cleats' },
  { civilianWord: 'Goggles', spyWord: 'Visor' },
  { civilianWord: 'Life Jacket', spyWord: 'Swim Vest' },
  { civilianWord: 'Tent', spyWord: 'Cabin' },
  { civilianWord: 'Compass', spyWord: 'Map' },
  { civilianWord: 'Binoculars', spyWord: 'Telescope' },
  { civilianWord: 'Trail', spyWord: 'Path' },
  { civilianWord: 'Waterfall', spyWord: 'Fountain' },
  { civilianWord: 'Volcano', spyWord: 'Geyser' },
  { civilianWord: 'Cave', spyWord: 'Mine' },
  { civilianWord: 'Cliff', spyWord: 'Ridge' },
  { civilianWord: 'Valley', spyWord: 'Meadow' },
  { civilianWord: 'Swamp', spyWord: 'Marsh' },
  { civilianWord: 'Pond', spyWord: 'Lagoon' },
  { civilianWord: 'Ocean', spyWord: 'Sea' },
  { civilianWord: 'Wave', spyWord: 'Tide' },
  { civilianWord: 'Thunder', spyWord: 'Lightning' },
  { civilianWord: 'Fog', spyWord: 'Mist' },
  { civilianWord: 'Cloud', spyWord: 'Smoke' },
  { civilianWord: 'Rainbow', spyWord: 'Aurora' },
  { civilianWord: 'Earthquake', spyWord: 'Landslide' },
  { civilianWord: 'Tornado', spyWord: 'Hurricane' },
  { civilianWord: 'Pebble', spyWord: 'Stone' },
  { civilianWord: 'Sand', spyWord: 'Gravel' },
  { civilianWord: 'Soil', spyWord: 'Clay' },
  { civilianWord: 'Moss', spyWord: 'Grass' },
  { civilianWord: 'Leaf', spyWord: 'Petal' },
  { civilianWord: 'Branch', spyWord: 'Vine' },
  { civilianWord: 'Root', spyWord: 'Stem' },
  { civilianWord: 'Flower', spyWord: 'Bouquet' },
  { civilianWord: 'Seed', spyWord: 'Nut' },
  { civilianWord: 'Beehive', spyWord: 'Ant Hill' },
  { civilianWord: 'Graduation', spyWord: 'Promotion' },
  { civilianWord: 'First Date', spyWord: 'Blind Date' },
  { civilianWord: 'Job Interview', spyWord: 'Audition' },
  { civilianWord: 'Conference', spyWord: 'Seminar' },
  { civilianWord: 'Workshop', spyWord: 'Training' },
  { civilianWord: 'Fundraiser', spyWord: 'Charity Event' },
  { civilianWord: 'Parade', spyWord: 'March' },
  { civilianWord: 'Picnic', spyWord: 'Barbecue' },
  { civilianWord: 'Brunch', spyWord: 'Buffet' },
  { civilianWord: 'Movie Night', spyWord: 'Watch Party' },
  { civilianWord: 'Game Night', spyWord: 'Trivia Night' },
  { civilianWord: 'Karaoke', spyWord: 'Open Mic' },
  { civilianWord: 'Talent Show', spyWord: 'Pageant' },
  { civilianWord: 'Award Show', spyWord: 'Premiere' },
  { civilianWord: 'Baby Shower', spyWord: 'Gender Reveal' },
  { civilianWord: 'Housewarming', spyWord: 'Open House' },
  { civilianWord: 'Garage Sale', spyWord: 'Flea Market' },
  { civilianWord: 'Black Friday', spyWord: 'Cyber Monday' },
  { civilianWord: 'New Year', spyWord: 'Countdown' },
  { civilianWord: 'Halloween', spyWord: 'Costume Party' },
  { civilianWord: 'Christmas', spyWord: 'Holiday Party' },
  { civilianWord: 'Valentine', spyWord: 'Date Night' },
  { civilianWord: 'April Fools', spyWord: 'Prank Day' },
  { civilianWord: 'Field Trip', spyWord: 'Excursion' },
  { civilianWord: 'Rehearsal', spyWord: 'Practice' },
  { civilianWord: 'Opening Night', spyWord: 'Finale' },
  { civilianWord: 'Press Conference', spyWord: 'Media Briefing' },
  { civilianWord: 'Election', spyWord: 'Referendum' },
  { civilianWord: 'Trial', spyWord: 'Hearing' },
  { civilianWord: 'Auction', spyWord: 'Bidding War' },
  { civilianWord: 'Treasure Hunt', spyWord: 'Scavenger Hunt' },
  { civilianWord: 'Escape Room', spyWord: 'Maze' },
  { civilianWord: 'Carnival', spyWord: 'Amusement Park' },
  { civilianWord: 'Fireworks', spyWord: 'Light Show' },
  { civilianWord: 'Food Tasting', spyWord: 'Wine Tasting' },
  { civilianWord: 'Cooking Class', spyWord: 'Baking Class' },
  { civilianWord: 'Book Club', spyWord: 'Study Group' },
  { civilianWord: 'Sleep Study', spyWord: 'Meditation Session' },
  { civilianWord: 'Photo Shoot', spyWord: 'Video Shoot' },
  { civilianWord: 'Racing Game', spyWord: 'Driving Simulator' },
  { civilianWord: 'Puzzle Game', spyWord: 'Escape Game' },
  { civilianWord: 'Board Game', spyWord: 'Card Game' },
  { civilianWord: 'Dice', spyWord: 'Dominoes' },
  { civilianWord: 'Arcade', spyWord: 'Pinball' },
  { civilianWord: 'Joystick', spyWord: 'Controller' },
  { civilianWord: 'Quest', spyWord: 'Mission' },
  { civilianWord: 'Level', spyWord: 'Stage' },
  { civilianWord: 'Boss Fight', spyWord: 'Final Battle' },
  { civilianWord: 'Power-Up', spyWord: 'Upgrade' },
  { civilianWord: 'Treasure Chest', spyWord: 'Loot Box' },
  { civilianWord: 'Spaceship', spyWord: 'Rocket' },
  { civilianWord: 'Satellite', spyWord: 'Space Station' },
  { civilianWord: 'Planet', spyWord: 'Moon' },
  { civilianWord: 'Galaxy', spyWord: 'Nebula' },
  { civilianWord: 'Time Machine', spyWord: 'Portal' },
  { civilianWord: 'Laser', spyWord: 'Flashlight' },
  { civilianWord: 'Shield', spyWord: 'Armor' },
  { civilianWord: 'Sword', spyWord: 'Spear' },
  { civilianWord: 'Bow', spyWord: 'Crossbow' },
  { civilianWord: 'Potion', spyWord: 'Elixir' },
  { civilianWord: 'Spellbook', spyWord: 'Diary' },
  { civilianWord: 'Map Room', spyWord: 'Control Room' },
  { civilianWord: 'Secret Door', spyWord: 'Hidden Passage' },
  { civilianWord: 'Safe', spyWord: 'Vault' },
  { civilianWord: 'Mission Briefing', spyWord: 'Team Meeting' },
  { civilianWord: 'Disguise', spyWord: 'Costume' },
  { civilianWord: 'Fingerprint', spyWord: 'Footprint' },
  { civilianWord: 'Password', spyWord: 'Passcode' },
  { civilianWord: 'Code Name', spyWord: 'Nickname' },
  { civilianWord: 'Walkie Talkie', spyWord: 'Radio' },
  { civilianWord: 'Envelope Seal', spyWord: 'Wax Stamp' },
  { civilianWord: 'Notebook Clue', spyWord: 'Sticky Note' },
  { civilianWord: 'Magnifying Glass', spyWord: 'Reading Glasses' },
  { civilianWord: 'Briefcase', spyWord: 'Toolbox' },
  { civilianWord: 'Trench Coat', spyWord: 'Rain Jacket' },
  { civilianWord: 'Sneak Attack', spyWord: 'Ambush' },
  { civilianWord: 'Alarm System', spyWord: 'Security Camera' },
  { civilianWord: 'Spotlight', spyWord: 'Searchlight' },
  { civilianWord: 'Fingerprint Scanner', spyWord: 'Face Scanner' },
  { civilianWord: 'Denim Jacket', spyWord: 'Leather Jacket' },
  { civilianWord: 'Hoodie', spyWord: 'Sweatshirt' },
  { civilianWord: 'T-Shirt', spyWord: 'Tank Top' },
  { civilianWord: 'Dress', spyWord: 'Gown' },
  { civilianWord: 'Suit', spyWord: 'Tuxedo' },
  { civilianWord: 'Tie', spyWord: 'Bow Tie' },
  { civilianWord: 'Scarf', spyWord: 'Shawl' },
  { civilianWord: 'Gloves', spyWord: 'Mittens' },
  { civilianWord: 'Sandals', spyWord: 'Slippers' },
  { civilianWord: 'Boots', spyWord: 'High Tops' },
  { civilianWord: 'Rain Boots', spyWord: 'Snow Boots' },
  { civilianWord: 'Belt', spyWord: 'Suspenders' },
  { civilianWord: 'Bracelet', spyWord: 'Watch' },
  { civilianWord: 'Necklace', spyWord: 'Pendant' },
  { civilianWord: 'Earrings', spyWord: 'Ear Cuffs' },
  { civilianWord: 'Ring', spyWord: 'Wedding Band' },
  { civilianWord: 'Backpack Strap', spyWord: 'Seatbelt' },
  { civilianWord: 'Luggage Tag', spyWord: 'Name Tag' },
  { civilianWord: 'Bathrobe', spyWord: 'Pajamas' },
  { civilianWord: 'Swimsuit', spyWord: 'Wetsuit' },
  { civilianWord: 'Apron', spyWord: 'Bib' },
  { civilianWord: 'Chef Hat', spyWord: 'Graduation Cap' },
  { civilianWord: 'Crown', spyWord: 'Tiara' },
  { civilianWord: 'Mask', spyWord: 'Face Shield' },
  { civilianWord: 'Perfume', spyWord: 'Cologne' },
  { civilianWord: 'Lipstick', spyWord: 'Lip Balm' },
  { civilianWord: 'Nail Polish', spyWord: 'Paint' },
  { civilianWord: 'Hairbrush', spyWord: 'Comb' },
  { civilianWord: 'Razor', spyWord: 'Shaver' },
  { civilianWord: 'Sunscreen', spyWord: 'Lotion' },
  { civilianWord: 'Passport', spyWord: 'Visa' },
  { civilianWord: 'Ticket', spyWord: 'Boarding Pass' },
  { civilianWord: 'Itinerary', spyWord: 'Schedule' },
  { civilianWord: 'Reservation', spyWord: 'Booking' },
  { civilianWord: 'Tour Guide', spyWord: 'Travel Agent' },
  { civilianWord: 'Souvenir', spyWord: 'Gift Shop Item' },
  { civilianWord: 'Postcard Stand', spyWord: 'Photo Booth' },
  { civilianWord: 'Currency Exchange', spyWord: 'Bank Teller' },
  { civilianWord: 'Customs', spyWord: 'Immigration' },
  { civilianWord: 'Baggage Claim', spyWord: 'Lost and Found' },
  { civilianWord: 'Carry-On', spyWord: 'Duffel Bag' },
  { civilianWord: 'Window Seat', spyWord: 'Aisle Seat' },
  { civilianWord: 'Cruise Ship', spyWord: 'Ferry' },
  { civilianWord: 'Speedboat', spyWord: 'Jet Ski' },
  { civilianWord: 'Taxi', spyWord: 'Rideshare' },
  { civilianWord: 'Bus', spyWord: 'Shuttle' },
  { civilianWord: 'Train', spyWord: 'Tram' },
  { civilianWord: 'Bicycle', spyWord: 'Motorcycle' },
  { civilianWord: 'Scooter Rental', spyWord: 'Bike Rental' },
  { civilianWord: 'Road Map', spyWord: 'GPS' },
  { civilianWord: 'Rest Stop', spyWord: 'Gas Station' },
  { civilianWord: 'Border Crossing', spyWord: 'Toll Gate' },
  { civilianWord: 'Camping Site', spyWord: 'RV Park' },
  { civilianWord: 'Hostel', spyWord: 'Motel' },
  { civilianWord: 'Room Service', spyWord: 'Delivery' },
  { civilianWord: 'Mini Bar', spyWord: 'Vending Machine' },
  { civilianWord: 'Concierge', spyWord: 'Receptionist' },
  { civilianWord: 'Travel Pillow', spyWord: 'Neck Pillow' },
  { civilianWord: 'Suitcase Wheel', spyWord: 'Shopping Cart Wheel' },
  { civilianWord: 'Landmark', spyWord: 'Monument' },
  { civilianWord: 'Textbook', spyWord: 'Workbook' },
  { civilianWord: 'Homework', spyWord: 'Assignment' },
  { civilianWord: 'Report Card', spyWord: 'Transcript' },
  { civilianWord: 'Backpack Pocket', spyWord: 'Locker' },
  { civilianWord: 'Whiteboard', spyWord: 'Chalkboard' },
  { civilianWord: 'Projector Screen', spyWord: 'Smart Board' },
  { civilianWord: 'School Bell', spyWord: 'Alarm Clock' },
  { civilianWord: 'Recess', spyWord: 'Lunch Break' },
  { civilianWord: 'Detention', spyWord: 'Timeout' },
  { civilianWord: 'Principal', spyWord: 'Dean' },
  { civilianWord: 'Class President', spyWord: 'Team Captain' },
  { civilianWord: 'Science Fair', spyWord: 'Art Exhibit' },
  { civilianWord: 'Group Project', spyWord: 'Presentation' },
  { civilianWord: 'Pop Quiz', spyWord: 'Practice Test' },
  { civilianWord: 'Final Exam', spyWord: 'Midterm' },
  { civilianWord: 'Essay', spyWord: 'Book Report' },
  { civilianWord: 'Flashcards', spyWord: 'Study Notes' },
  { civilianWord: 'Calculator App', spyWord: 'Spreadsheet' },
  { civilianWord: 'Graduation Photo', spyWord: 'Yearbook' },
  { civilianWord: 'School Bus', spyWord: 'Field Trip Van' },
  { civilianWord: 'Chemistry Lab', spyWord: 'Science Room' },
  { civilianWord: 'Art Room', spyWord: 'Music Room' },
  { civilianWord: 'Band Practice', spyWord: 'Choir Practice' },
  { civilianWord: 'Debate Club', spyWord: 'Drama Club' },
  { civilianWord: 'School Nurse', spyWord: 'Guidance Counselor' },
  { civilianWord: 'Dormitory', spyWord: 'Boarding House' },
  { civilianWord: 'Scholarship', spyWord: 'Grant' },
  { civilianWord: 'Tuition', spyWord: 'Enrollment Fee' },
  { civilianWord: 'Online Class', spyWord: 'Webinar' },
  { civilianWord: 'Library Card', spyWord: 'Student ID' },
  { civilianWord: 'Email', spyWord: 'Text Message' },
  { civilianWord: 'Video Call', spyWord: 'Voice Call' },
  { civilianWord: 'Group Chat', spyWord: 'Forum' },
  { civilianWord: 'Profile Picture', spyWord: 'Avatar' },
  { civilianWord: 'Username', spyWord: 'Display Name' },
  { civilianWord: 'Notification', spyWord: 'Reminder' },
  { civilianWord: 'Search Engine', spyWord: 'Browser' },
  { civilianWord: 'Website', spyWord: 'Landing Page' },
  { civilianWord: 'App Store', spyWord: 'Play Store' },
  { civilianWord: 'Download', spyWord: 'Upload' },
  { civilianWord: 'Cloud Storage', spyWord: 'Hard Drive' },
  { civilianWord: 'Screenshot', spyWord: 'Screen Recording' },
  { civilianWord: 'Password Manager', spyWord: 'Notebook' },
  { civilianWord: 'Two-Factor Code', spyWord: 'PIN' },
  { civilianWord: 'Fingerprint Unlock', spyWord: 'Face Unlock' },
  { civilianWord: 'QR Code', spyWord: 'Barcode' },
  { civilianWord: 'Bluetooth', spyWord: 'Wi-Fi' },
  { civilianWord: 'Airplane Mode', spyWord: 'Do Not Disturb' },
  { civilianWord: 'Battery Saver', spyWord: 'Low Power Mode' },
  { civilianWord: 'Dark Mode', spyWord: 'Night Shift' },
  { civilianWord: 'Voice Assistant', spyWord: 'Chatbot' },
  { civilianWord: 'Playlist', spyWord: 'Album' },
  { civilianWord: 'Podcast Episode', spyWord: 'Radio Segment' },
  { civilianWord: 'Livestream', spyWord: 'Premiere' },
  { civilianWord: 'Hashtag', spyWord: 'Caption' },
  { civilianWord: 'Emoji', spyWord: 'Sticker' },
  { civilianWord: 'Filter', spyWord: 'Preset' },
  { civilianWord: 'Timeline', spyWord: 'News Feed' },
  { civilianWord: 'Bookmark', spyWord: 'Favorite' },
  { civilianWord: 'Shopping Cart', spyWord: 'Wishlist' },
  { civilianWord: 'Receipt', spyWord: 'Invoice' },
  { civilianWord: 'Frying Pan', spyWord: 'Wok' },
  { civilianWord: 'Saucepan', spyWord: 'Pot' },
  { civilianWord: 'Kettle', spyWord: 'Coffee Maker' },
  { civilianWord: 'Blender', spyWord: 'Food Processor' },
  { civilianWord: 'Microwave', spyWord: 'Toaster Oven' },
  { civilianWord: 'Oven', spyWord: 'Air Fryer' },
  { civilianWord: 'Refrigerator', spyWord: 'Freezer' },
  { civilianWord: 'Dishwasher', spyWord: 'Washing Machine' },
  { civilianWord: 'Sink', spyWord: 'Wash Basin' },
  { civilianWord: 'Cutting Board', spyWord: 'Serving Tray' },
  { civilianWord: 'Knife', spyWord: 'Peeler' },
  { civilianWord: 'Fork', spyWord: 'Chopsticks' },
  { civilianWord: 'Spoon', spyWord: 'Ladle' },
  { civilianWord: 'Plate', spyWord: 'Bowl' },
  { civilianWord: 'Mug', spyWord: 'Cup' },
  { civilianWord: 'Glass', spyWord: 'Tumbler' },
  { civilianWord: 'Napkin', spyWord: 'Tissue' },
  { civilianWord: 'Tablecloth', spyWord: 'Placemat' },
  { civilianWord: 'Trash Can', spyWord: 'Recycle Bin' },
  { civilianWord: 'Laundry Basket', spyWord: 'Hamper' },
  { civilianWord: 'Iron', spyWord: 'Steamer' },
  { civilianWord: 'Clothesline', spyWord: 'Drying Rack' },
  { civilianWord: 'Hanger', spyWord: 'Coat Hook' },
  { civilianWord: 'Doormat', spyWord: 'Rug' },
  { civilianWord: 'Bookshelf', spyWord: 'Display Cabinet' },
  { civilianWord: 'Nightstand', spyWord: 'Side Table' },
  { civilianWord: 'Dresser', spyWord: 'Wardrobe' },
  { civilianWord: 'Ceiling Fan', spyWord: 'Air Conditioner' },
  { civilianWord: 'Heater', spyWord: 'Fireplace' },
  { civilianWord: 'Door Handle', spyWord: 'Cabinet Knob' },
  { civilianWord: 'Staircase', spyWord: 'Ladder' },
  { civilianWord: 'Mailbox', spyWord: 'Parcel Box' },
  { civilianWord: 'Garden Hose', spyWord: 'Sprinkler' },
  { civilianWord: 'Flower Pot', spyWord: 'Vase' },
  { civilianWord: 'Lawn Mower', spyWord: 'Leaf Blower' },
  { civilianWord: 'Toolbox', spyWord: 'First Aid Kit' },
  { civilianWord: 'Hammer', spyWord: 'Mallet' },
  { civilianWord: 'Screwdriver', spyWord: 'Wrench' },
  { civilianWord: 'Nail', spyWord: 'Screw' },
  { civilianWord: 'Extension Cord', spyWord: 'Power Strip' },
  { civilianWord: 'Flashlight', spyWord: 'Headlamp' },
  { civilianWord: 'Jeepney', spyWord: 'Bus' },
  { civilianWord: 'Tricycle', spyWord: 'Tuk-Tuk' },
  { civilianWord: 'Sari-Sari Store', spyWord: 'Convenience Store' },
  { civilianWord: 'Wet Market', spyWord: 'Fish Market' },
  { civilianWord: 'Rice Cooker', spyWord: 'Pressure Cooker' },
  { civilianWord: 'Adobo', spyWord: 'Menudo' },
  { civilianWord: 'Sinigang', spyWord: 'Tinola' },
  { civilianWord: 'Lechon', spyWord: 'Roast Pork' },
  { civilianWord: 'Halo-Halo', spyWord: 'Mais Con Yelo' },
  { civilianWord: 'Taho', spyWord: 'Soy Milk' },
  { civilianWord: 'Lumpia', spyWord: 'Spring Roll' },
  { civilianWord: 'Pancit', spyWord: 'Chow Mein' },
  { civilianWord: 'Kare-Kare', spyWord: 'Peanut Stew' },
  { civilianWord: 'Sisig', spyWord: 'Chopped Pork' },
  { civilianWord: 'Bibingka', spyWord: 'Rice Cake' },
  { civilianWord: 'Balut', spyWord: 'Boiled Egg' },
  { civilianWord: 'Buko Juice', spyWord: 'Coconut Water' },
  { civilianWord: 'Calamansi', spyWord: 'Lime' },
  { civilianWord: 'Mango Float', spyWord: 'Icebox Cake' },
  { civilianWord: 'Jollibee', spyWord: "McDonald's" },
  { civilianWord: 'Basket', spyWord: 'Crate' },
  { civilianWord: 'Envelope', spyWord: 'Folder' },
  { civilianWord: 'Candle', spyWord: 'Torch' },
  { civilianWord: 'Picture Frame', spyWord: 'Poster' },
  { civilianWord: 'Gift Wrap', spyWord: 'Ribbon' },
  { civilianWord: 'Birthday Cake', spyWord: 'Wedding Cake' },
  { civilianWord: 'Invitation', spyWord: 'Announcement' },
  { civilianWord: 'Confetti', spyWord: 'Glitter' },
  { civilianWord: 'Balloon', spyWord: 'Lantern' },
  { civilianWord: 'Bouquet', spyWord: 'Wreath' },
  { civilianWord: 'Photo Album', spyWord: 'Scrapbook' },
  { civilianWord: 'Diary', spyWord: 'Memoir' },
  { civilianWord: 'Comic Book', spyWord: 'Graphic Novel' },
  { civilianWord: 'Novel', spyWord: 'Short Story' },
  { civilianWord: 'Newspaper', spyWord: 'Magazine' },
  { civilianWord: 'Recipe', spyWord: 'Menu' },
  { civilianWord: 'Coupon', spyWord: 'Voucher' },
  { civilianWord: 'Business Card', spyWord: 'Name Plate' },
  { civilianWord: 'Contract', spyWord: 'Agreement' },
  { civilianWord: 'Certificate', spyWord: 'Diploma' },
  { civilianWord: 'Cough', spyWord: 'Sneeze' },
  { civilianWord: 'Headache', spyWord: 'Migraine' },
  { civilianWord: 'Fever', spyWord: 'Chills' },
  { civilianWord: 'Bandage', spyWord: 'Gauze' },
  { civilianWord: 'Thermometer', spyWord: 'Blood Pressure Cuff' },
  { civilianWord: 'Medicine', spyWord: 'Vitamin' },
  { civilianWord: 'Wheelchair', spyWord: 'Stroller' },
  { civilianWord: 'Crutches', spyWord: 'Cane' },
  { civilianWord: 'Ambulance', spyWord: 'Fire Truck' },
  { civilianWord: 'Emergency Room', spyWord: 'Urgent Care' },
  { civilianWord: 'Prescription', spyWord: 'Medical Note' },
  { civilianWord: 'X-Ray', spyWord: 'Ultrasound' },
  { civilianWord: 'Stethoscope', spyWord: 'Thermometer' },
  { civilianWord: 'Hospital Bed', spyWord: 'Examination Table' },
  { civilianWord: 'Waiting Room', spyWord: 'Reception Area' },
  { civilianWord: 'Eye Chart', spyWord: 'Vision Test' },
  { civilianWord: 'Toothpaste', spyWord: 'Mouthwash' },
  { civilianWord: 'Vaccine', spyWord: 'Injection' },
  { civilianWord: 'Checkup', spyWord: 'Consultation' },
  { civilianWord: 'Surgery', spyWord: 'Operation' },
  { civilianWord: 'Guitar', spyWord: 'Ukulele' },
  { civilianWord: 'Violin', spyWord: 'Cello' },
  { civilianWord: 'Drums', spyWord: 'Bongos' },
  { civilianWord: 'Trumpet', spyWord: 'Trombone' },
  { civilianWord: 'Flute', spyWord: 'Recorder' },
  { civilianWord: 'Saxophone', spyWord: 'Clarinet' },
  { civilianWord: 'Microphone Stand', spyWord: 'Music Stand' },
  { civilianWord: 'Stage Lights', spyWord: 'Spotlights' },
  { civilianWord: 'Encore', spyWord: 'Curtain Call' },
  { civilianWord: 'Solo', spyWord: 'Duet' },
  { civilianWord: 'Chorus', spyWord: 'Verse' },
  { civilianWord: 'Beat', spyWord: 'Rhythm' },
  { civilianWord: 'Lyrics', spyWord: 'Poem' },
  { civilianWord: 'Album Cover', spyWord: 'Poster Art' },
  { civilianWord: 'Vinyl Record', spyWord: 'CD' },
  { civilianWord: 'Headliner', spyWord: 'Opening Act' },
  { civilianWord: 'Backstage', spyWord: 'Green Room' },
  { civilianWord: 'Dance Floor', spyWord: 'Stage' },
  { civilianWord: 'Ballet', spyWord: 'Contemporary Dance' },
  { civilianWord: 'Hip-Hop', spyWord: 'Breakdance' },
  { civilianWord: 'Detective Board', spyWord: 'Mood Board' },
  { civilianWord: 'Evidence Bag', spyWord: 'Plastic Bag' },
  { civilianWord: 'Case File', spyWord: 'Folder' },
  { civilianWord: 'Witness', spyWord: 'Suspect' },
  { civilianWord: 'Alibi', spyWord: 'Excuse' },
  { civilianWord: 'Interrogation', spyWord: 'Interview' },
  { civilianWord: 'Hidden Camera', spyWord: 'Security Camera' },
  { civilianWord: 'Secret Agent', spyWord: 'Bodyguard' },
  { civilianWord: 'Rooftop Chase', spyWord: 'Car Chase' },
  { civilianWord: 'Getaway Car', spyWord: 'Taxi' },
  { civilianWord: 'Laser Grid', spyWord: 'Tripwire' },
  { civilianWord: 'Decoder', spyWord: 'Calculator' },
  { civilianWord: 'Invisible Ink', spyWord: 'Highlighter' },
  { civilianWord: 'Classified File', spyWord: 'Private Journal' },
  { civilianWord: 'Safe House', spyWord: 'Guest House' },
  { civilianWord: 'Drop Point', spyWord: 'Meeting Spot' },
  { civilianWord: 'Surveillance Van', spyWord: 'Delivery Van' },
  { civilianWord: 'Earpiece', spyWord: 'Earbud' },
  { civilianWord: 'Bug Detector', spyWord: 'Metal Detector' },
  { civilianWord: 'Fake Passport', spyWord: 'Student ID' },
  { civilianWord: 'Dragonfly', spyWord: 'Butterfly' },
  { civilianWord: 'Dolphin', spyWord: 'Whale' },
  { civilianWord: 'Penguin', spyWord: 'Seal' },
  { civilianWord: 'Eagle', spyWord: 'Hawk' },
  { civilianWord: 'Owl', spyWord: 'Bat' },
  { civilianWord: 'Tiger', spyWord: 'Leopard' },
  { civilianWord: 'Lion', spyWord: 'Cheetah' },
  { civilianWord: 'Elephant', spyWord: 'Rhino' },
  { civilianWord: 'Giraffe', spyWord: 'Camel' },
  { civilianWord: 'Kangaroo', spyWord: 'Wallaby' },
  { civilianWord: 'Horse', spyWord: 'Donkey' },
  { civilianWord: 'Goat', spyWord: 'Sheep' },
  { civilianWord: 'Duck', spyWord: 'Goose' },
  { civilianWord: 'Chicken', spyWord: 'Turkey' },
  { civilianWord: 'Goldfish', spyWord: 'Koi' },
  { civilianWord: 'Shark', spyWord: 'Swordfish' },
  { civilianWord: 'Octopus', spyWord: 'Squid' },
  { civilianWord: 'Crab', spyWord: 'Lobster' },
  { civilianWord: 'Turtle', spyWord: 'Tortoise' },
  { civilianWord: 'Frog', spyWord: 'Toad' },
  { civilianWord: 'Hot Air Balloon', spyWord: 'Parachute' },
  { civilianWord: 'Roller Coaster', spyWord: 'Ferris Wheel' },
  { civilianWord: 'Carousel', spyWord: 'Merry-Go-Round' },
  { civilianWord: 'Bumper Cars', spyWord: 'Go-Karts' },
  { civilianWord: 'Haunted House', spyWord: 'Escape Room' },
  { civilianWord: 'Magic Show', spyWord: 'Puppet Show' },
  { civilianWord: 'Circus Tent', spyWord: 'Big Top' },
  { civilianWord: 'Clown', spyWord: 'Mime' },
  { civilianWord: 'Acrobat', spyWord: 'Stunt Performer' },
  { civilianWord: 'Fire Breather', spyWord: 'Juggler' },
  { civilianWord: 'Ticket Booth', spyWord: 'Box Office' },
  { civilianWord: 'Prize Booth', spyWord: 'Game Stall' },
  { civilianWord: 'Cotton Candy', spyWord: 'Marshmallow' },
  { civilianWord: 'Snow Cone', spyWord: 'Slushie' },
  { civilianWord: 'Arcade Token', spyWord: 'Game Ticket' },
  { civilianWord: 'Ferris Wheel Seat', spyWord: 'Cable Car' },
  { civilianWord: 'Water Slide', spyWord: 'Slip and Slide' },
  { civilianWord: 'Wave Pool', spyWord: 'Lazy River' },
  { civilianWord: 'Zipline', spyWord: 'Rope Bridge' },
  { civilianWord: 'Claw Machine', spyWord: 'Vending Machine' },
]

export function getRandomWordPair() {
  return wordPairs[Math.floor(Math.random() * wordPairs.length)]
}
