export const GAME_ERROR = {
  CANNOT_START_DISCUSSION_WITHOUT_PLAYERS: 'Cannot start discussion without players.',
  DISCUSSION_STATE_INCOMPLETE: 'Discussion state is incomplete.',
  HOST_NOT_IN_ROOM: 'Host does not belong to this room.',
  PLAYER_NOT_IN_ROOM: 'Player does not belong to this room.',
  HOST_PLAYER_NOT_FOUND: 'Host player not found.',
  INVALID_PLAYER_COUNT: 'Invalid player count.',
  INVALID_SPY_COUNT: 'Invalid spy count.',
  NOT_ACTIVE_DISCUSSION_PLAYER: 'Only the active player can end their turn.',
  NOT_CURRENT_ROOM_ROUND: 'Round does not belong to current room state.',
  NOT_HOST: 'Only the host can start the game.',
  ROLE_ASSIGNMENT_NOT_FOUND: 'Role assignment not found.',
  ROOM_NOT_FOUND: 'Room not found.',
  ROOM_NOT_IN_CURRENT_DISCUSSION: 'Room is not in the current discussion.',
  ROOM_NOT_IN_CURRENT_VOTING: 'Room is not in the current voting.',
  ROOM_NOT_IN_LOBBY: 'Room is not in the lobby.',
  ROUND_NOT_FOUND: 'Round not found.',
  TARGET_NOT_IN_ROOM: 'Target not in room.',
  VOTER_NOT_IN_ROOM: 'Voter not in room.',
  CANNOT_VOTE_SELF: 'You cannot vote yourself.',
  TIED_CANDIDATE_CANNOT_VOTE: 'Tied candidates cannot vote during the runoff.',
  VOTING_NOT_COMPLETE: 'Voting not complete.',
  ROOM_NOT_IN_RESULTS: 'Room is not in the results phase.',
  TARGET_NOT_TIE_CANDIDATE: 'Target is not a tie candidate',
  INVALID_STATUS: 'Invalid status.',
  GENERIC_ERROR: 'Something went wrong.',
  ROOM_NOT_IN_CATEGORY_SUGGESTION: 'Room is not in the category suggestion phase.',
  ROOM_NOT_IN_CATEGORY_VOTING: 'Room is not in the category voting phase.',
  ROOM_NOT_IN_WORD_SUBMISSION: 'Room is not in the word submission phase.',
  EMPTY_SUBMISSION: 'Submission cannot be empty.',
  CANNOT_VOTE_OWN_CATEGORY: 'You cannot vote for your own category.',
  SUGGESTION_NOT_FOUND: 'Category suggestion not found.',
} as const
